[nvim-base-16]
src.git = "https://github.com/RRethy/nvim-base16"
fetch.github = "RRethy/nvim-base16"

[incline]
src.git = "https://github.com/b0o/incline.nvim"
fetch.github = "b0o/incline.nvim"

[scope]
src.git = "https://github.com/tiagovla/scope.nvim"
fetch.github = "tiagovla/scope.nvim"

[sixelpreview]
src.git = "https://github.com/sioodmy/sixelpreview.nvim"
fetch.github = "sioodmy/sixelpreview.nvim"
